version: '3.2'
services:
  master:
    image: botrandom:rename
    user: "node"
    volumes:
      - type: bind
        source: ../../Results/${BOTRANDOM_EXPERIMENT_NAME}
        target: /home/node/app/output
    deploy:
      restart_policy:
        condition: none
    command:
      - bash
      - -c
      - |
        npm start -- -n Master --address master -p 20001 -o 150000 --delay 10000 --time 200 -s 10000 --deletion 20 --deplacement 5 --operation 15000 --strategy rls && sync
  bot1:
    depends_on:
      - master
    image: botrandom:rename
    user: "node"
    volumes:
      - type: bind
        source: ../../Results/${BOTRANDOM_EXPERIMENT_NAME}
        target: /home/node/app/output
    deploy:
      restart_policy:
        condition: none
    command:
      - bash
      - -c
      - |
        npm start -- -n Bot1 -m ws://master:20001 --address bot1 -p 20001 -o 150005 --delay 10000 --time 200 -s 150005 --deletion 20 --deplacement 5 --operation 15000 --strategy rls && sync
  bot2:
    depends_on:
      - master
    image: botrandom:rename
    user: "node"
    volumes:
      - type: bind
        source: ../../Results/${BOTRANDOM_EXPERIMENT_NAME}
        target: /home/node/app/output
    deploy:
      restart_policy:
        condition: none
    command:
      - bash
      - -c
      - |
        npm start -- -n Bot2 -m ws://master:20001 --address bot2 -p 20001 -o 150005 --delay 10000 --time 200 -s 150005 --deletion 20 --deplacement 5 --operation 15000 --strategy rls && sync
  bot3:
    depends_on:
      - master
    image: botrandom:rename
    user: "node"
    volumes:
      - type: bind
        source: ../../Results/${BOTRANDOM_EXPERIMENT_NAME}
        target: /home/node/app/output
    deploy:
      restart_policy:
        condition: none
    command:
      - bash
      - -c
      - |
        npm start -- -n Bot3 -m ws://master:20001 --address bot3 -p 20001 -o 150005 --delay 10000 --time 200 -s 150005 --deletion 20 --deplacement 5 --operation 15000 --strategy rls && sync
  bot4:
    depends_on:
      - master
    image: botrandom:rename
    user: "node"
    volumes:
      - type: bind
        source: ../../Results/${BOTRANDOM_EXPERIMENT_NAME}
        target: /home/node/app/output
    deploy:
      restart_policy:
        condition: none
    command:
      - bash
      - -c
      - |
        npm start -- -n Bot4 -m ws://master:20001 --address bot4 -p 20001 -o 150005 --delay 10000 --time 200 -s 150005 --deletion 20 --deplacement 5 --operation 15000 --strategy rls && sync
  bot5:
    depends_on:
      - master
    image: botrandom:rename
    user: "node"
    volumes:
      - type: bind
        source: ../../Results/${BOTRANDOM_EXPERIMENT_NAME}
        target: /home/node/app/output
    deploy:
      restart_policy:
        condition: none
    command:
      - bash
      - -c
      - |
        npm start -- -n Bot5 -m ws://master:20001 --address bot5 -p 20001 -o 150005 --delay 10000 --time 200 -s 150005 --deletion 20 --deplacement 5 --operation 15000 --strategy rls && sync
  bot6:
    depends_on:
      - master
    image: botrandom:rename
    user: "node"
    volumes:
      - type: bind
        source: ../../Results/${BOTRANDOM_EXPERIMENT_NAME}
        target: /home/node/app/output
    deploy:
      restart_policy:
        condition: none
    command:
      - bash
      - -c
      - |
        npm start -- -n Bot6 -m ws://master:20001 --address bot6 -p 20001 -o 150005 --delay 10000 --time 200 -s 150005 --deletion 20 --deplacement 5 --operation 15000 --strategy rls && sync
  bot7:
    depends_on:
      - master
    image: botrandom:rename
    user: "node"
    volumes:
      - type: bind
        source: ../../Results/${BOTRANDOM_EXPERIMENT_NAME}
        target: /home/node/app/output
    deploy:
      restart_policy:
        condition: none
    command:
      - bash
      - -c
      - |
        npm start -- -n Bot7 -m ws://master:20001 --address bot7 -p 20001 -o 150005 --delay 10000 --time 200 -s 150005 --deletion 20 --deplacement 5 --operation 15000 --strategy rls && sync
  bot8:
    depends_on:
      - master
    image: botrandom:rename
    user: "node"
    volumes:
      - type: bind
        source: ../../Results/${BOTRANDOM_EXPERIMENT_NAME}
        target: /home/node/app/output
    deploy:
      restart_policy:
        condition: none
    command:
      - bash
      - -c
      - |
        npm start -- -n Bot8 -m ws://master:20001 --address bot8 -p 20001 -o 150005 --delay 10000 --time 200 -s 150005 --deletion 20 --deplacement 5 --operation 15000 --strategy rls && sync
  bot9:
    depends_on:
      - master
    image: botrandom:rename
    user: "node"
    volumes:
      - type: bind
        source: ../../Results/${BOTRANDOM_EXPERIMENT_NAME}
        target: /home/node/app/output
    deploy:
      restart_policy:
        condition: none
    command:
      - bash
      - -c
      - |
        npm start -- -n Bot9 -m ws://master:20001 --address bot9 -p 20001 -o 150005 --delay 10000 --time 200 -s 150005 --deletion 20 --deplacement 5 --operation 15000 --strategy rls && sync
