version: '3.2'
services: 
  master:
    image: botrandom:latest
    user: "node"
    volumes:
      - type: bind
        source: ../../Results/${BOTRANDOM_EXPERIMENT_NAME}
        target: /home/node/app/output
    command:
      - bash
      - -c
      - |
        npm start -- -n Jean --address master -p 20001 -o 300 --delay 10000 --time 500 -s 100 --deletion 20 --deplacement 5 --operation 100
  bot1:
    depends_on:
      - master
    image: botrandom:latest
    user: "node"
    volumes:
      - type: bind
        source: ../../Results/${BOTRANDOM_EXPERIMENT_NAME}
        target: /home/node/app/output
    command:
      - bash
      - -c
      - |
        npm start -- -n Paul -m ws://master:20001 --address bot1 -p 20001 -o 300 --delay 10000 --time 500 -s 100 --deletion 20 --deplacement 5 --operation 100
  bot2:
    depends_on:
      - master
    image: botrandom:latest
    user: "node"
    volumes:
      - type: bind
        source: ../../Results/${BOTRANDOM_EXPERIMENT_NAME}
        target: /home/node/app/output
    command:
      - bash
      - -c
      - |
        npm start -- -n Arthur -m ws://master:20001 --address bot2 -p 20001 -o 300 --delay 10000 --time 500 -s 100 --deletion 20 --deplacement 5 --operation 100
