version: '3.2'
services: 
  Master:
    image: botrandom:latest
    user: "node"
    volumes:
      - type: bind
        source: ../../Results/${BOTRANDOM_EXPERIMENT_NAME}
        target: /home/node/app/output
    deploy:
      restart_policy:
        condition: none
    command:
      - bash
      - -c
      - |
        npm start -- -n Master --address Master -p 20001 -o 1000000 --delay 10000 --time 500 -s 50000 --deletion 20 --deplacement 5 --operation 100000 --strategy dls
  Bot1:
    depends_on:
      - Master
    image: botrandom:latest
    user: "node"
    volumes:
      - type: bind
        source: ../../Results/${BOTRANDOM_EXPERIMENT_NAME}
        target: /home/node/app/output
    deploy:
      restart_policy:
        condition: none
    command:
      - bash
      - -c
      - |
        npm start -- -n Bot1 -m ws://master:20001 --address Bot1 -p 20001 -o 1000000 --delay 10000 --time 500 -s 50000 --deletion 20 --deplacement 5 --operation 100000 --strategy dls
  Bot2:
    depends_on:
      - Master
    image: botrandom:latest
    user: "node"
    volumes:
      - type: bind
        source: ../../Results/${BOTRANDOM_EXPERIMENT_NAME}
        target: /home/node/app/output
    deploy:
      restart_policy:
        condition: none
    command:
      - bash
      - -c
      - |
        npm start -- -n Bot2 -m ws://master:20001 --address Bot2 -p 20001 -o 1000000 --delay 10000 --time 500 -s 50000 --deletion 20 --deplacement 5 --operation 100000 --strategy dls
  Bot3:
    depends_on:
      - Master
    image: botrandom:latest
    user: "node"
    volumes:
      - type: bind
        source: ../../Results/${BOTRANDOM_EXPERIMENT_NAME}
        target: /home/node/app/output
    deploy:
      restart_policy:
        condition: none
    command:
      - bash
      - -c
      - |
        npm start -- -n Bot3 -m ws://master:20001 --address Bot3 -p 20001 -o 1000000 --delay 10000 --time 500 -s 50000 --deletion 20 --deplacement 5 --operation 100000 --strategy dls
  Bot4:
    depends_on:
      - Master
    image: botrandom:latest
    user: "node"
    volumes:
      - type: bind
        source: ../../Results/${BOTRANDOM_EXPERIMENT_NAME}
        target: /home/node/app/output
    deploy:
      restart_policy:
        condition: none
    command:
      - bash
      - -c
      - |
        npm start -- -n Bot4 -m ws://master:20001 --address Bot4 -p 20001 -o 1000000 --delay 10000 --time 500 -s 50000 --deletion 20 --deplacement 5 --operation 100000 --strategy dls
  Bot5:
    depends_on:
      - Master
    image: botrandom:latest
    user: "node"
    volumes:
      - type: bind
        source: ../../Results/${BOTRANDOM_EXPERIMENT_NAME}
        target: /home/node/app/output
    deploy:
      restart_policy:
        condition: none
    command:
      - bash
      - -c
      - |
        npm start -- -n Bot5 -m ws://master:20001 --address Bot5 -p 20001 -o 1000000 --delay 10000 --time 500 -s 50000 --deletion 20 --deplacement 5 --operation 100000 --strategy dls
  Bot6:
    depends_on:
      - Master
    image: botrandom:latest
    user: "node"
    volumes:
      - type: bind
        source: ../../Results/${BOTRANDOM_EXPERIMENT_NAME}
        target: /home/node/app/output
    deploy:
      restart_policy:
        condition: none
    command:
      - bash
      - -c
      - |
        npm start -- -n Bot6 -m ws://master:20001 --address Bot6 -p 20001 -o 1000000 --delay 10000 --time 500 -s 50000 --deletion 20 --deplacement 5 --operation 100000 --strategy dls
  Bot7:
    depends_on:
      - Master
    image: botrandom:latest
    user: "node"
    volumes:
      - type: bind
        source: ../../Results/${BOTRANDOM_EXPERIMENT_NAME}
        target: /home/node/app/output
    deploy:
      restart_policy:
        condition: none
    command:
      - bash
      - -c
      - |
        npm start -- -n Bot7 -m ws://master:20001 --address Bot7 -p 20001 -o 1000000 --delay 10000 --time 500 -s 50000 --deletion 20 --deplacement 5 --operation 100000 --strategy dls
  Bot8:
    depends_on:
      - Master
    image: botrandom:latest
    user: "node"
    volumes:
      - type: bind
        source: ../../Results/${BOTRANDOM_EXPERIMENT_NAME}
        target: /home/node/app/output
    deploy:
      restart_policy:
        condition: none
    command:
      - bash
      - -c
      - |
        npm start -- -n Bot8 -m ws://master:20001 --address Bot8 -p 20001 -o 1000000 --delay 10000 --time 500 -s 50000 --deletion 20 --deplacement 5 --operation 100000 --strategy dls
  Bot9:
    depends_on:
      - Master
    image: botrandom:latest
    user: "node"
    volumes:
      - type: bind
        source: ../../Results/${BOTRANDOM_EXPERIMENT_NAME}
        target: /home/node/app/output
    deploy:
      restart_policy:
        condition: none
    command:
      - bash
      - -c
      - |
        npm start -- -n Bot9 -m ws://master:20001 --address Bot9 -p 20001 -o 1000000 --delay 10000 --time 500 -s 50000 --deletion 20 --deplacement 5 --operation 100000 --strategy dls
