version: '3.2'
services:
  master:
    image: resultexploit:latest
    user: 'node'
    volumes:
      - type: bind
        source: ./output
        target: /home/node/app/output
      - type: bind
        source: ./input
        target: /home/node/app/input
    deploy:
      restart_policy:
        condition: none
    command:
      - bash
      - -c
      - |
        npm start -- -s ./input/snapshot.json -c ./input/config.json
